server:
  port: 8086
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:54320/task_management
    username: postgres
    password: postgres
  liquibase:
    change-log: liquibase/changelog-master.yml
    enabled: true
    drop-first: false
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    key: c2VjcmV0X2tleV9vZl91c2VyX2xvZ2luX3JlZ2lzdGVyX2FuZF90YXNrX21hbmFnZW1lbnRfc3lzdGVtX2Jhc2U2NF9mb3JtYXQ=
    accessToken:
       time: 15
    refreshToken:
       time: 1440
  mail:
    host: smtp.gmail.com
    port: 587
    username: kselminaz@gmail.com
    password: rtpztuzcwdozqrdq
    properties:
      mail:
        protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
            required: true


